pipeline {
    agent any

  tools {
    jdk 'jdk17'
    maven 'mvn3' 
  }

  environment{
    SCANNER_HOME = tool 'sonar-scanner'
  }

  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/venkat8977/boardgame1.git'
      }
    }

    stage('Compile') {
      steps {
        sh 'mvn compile'
      }
    }
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }

    stage('SonarQube Analysis'){
        steps {
            withSonarQubeEnv('sonar-server') {
                sh '''
                $SCANNER_HOME/bin/sonar-scanner \
                  -Dsonar.projectName=boardgame \
                  -Dsonar.projectKey=boardgame \
                  -Dsonar.java.binaries=target
                '''

            }
        } 
    }

    stage('Quality Gate') {
        steps {
            timeout(time: 3, unit: 'MINUTES') {
                waitForQualityGate abortPipeline: true
            }
        }
    }

    stage('Build Docker Image'){
        steps{
           sh "docker build -f devops/Dockerfile -t venky005/boardgame1:${BUILD_NUMBER} ."
        }
    }

    stage('Trivy Image Scan'){
        steps{
           sh "trivy image --severity HIGH,CRITICAL venky005/boardgame1:${BUILD_NUMBER}"
        }
    }

    stage('Push to Nexus') {
        steps {
            withCredentials([
                usernamePassword(credentialsId: 'nexus-cred', usernameVariable: 'NU', passwordVariable: 'NP'),
                string(credentialsId: 'nexus-registry', variable: 'REGISTRY')
            ])  {
                sh '''
                    docker tag venky005/boardgame1:${BUILD_NUMBER} $REGISTRY/venky005/boardgame1:${BUILD_NUMBER}
                    echo "$NP" | docker login $REGISTRY -u "$NU" --password-stdin
                    docker push $REGISTRY/venky005/boardgame1:${BUILD_NUMBER}
                '''
            }
        }
    }

    stage('Update Helm values') {
        steps {
            withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GU', passwordVariable: 'GP')]) {
                sh '''
                    git config user.email "jenkins@ci.com"
                    git config user.name "venkat"

                    sed -i "s|tag: .*|tag: \\"${BUILD_NUMBER}\\"|" devops/helm/boardgame/values.yaml

                    git add devops/helm/boardgame/values.yaml
                    git commit -m "Update image tag to ${BUILD_NUMBER}"
                    git push https://${GU}:${GP}@github.com/venkat8977/boardgame1.git main 
                '''
            }
        }
    }
  } 
}


