pipeline {
    agent any

  tools {
    jdk 'jdk17'
    maven 'mvn3' 
  }

  environment{
    SCANNER_HOME = tool 'sonar-scanner'
  }

  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/venkat8977/boardgame1.git'
      }
    }

    stage('Compile') {
      steps {
        sh 'mvn compile'
      }
    }
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }

    stage('SonarQube Analysis'){
        steps {
            withSonarQubeEnv('sonar-server') {
                sh '''
                $SCANNER_HOME/bin/sonar-scanner \
                  -Dsonar.projectName=boardgame \
                  -Dsonar.projectKey=boardgame \
                  -Dsonar.java.binaries=target
                '''

            }
        } 
    }

    stage('Quality Gate') {
        steps {
            timeout(time: 3, unit: 'MINUTES') {
                waitForQualityGate abortPipeline: true
            }
        }
    }

    stage('Build Docker Image'){
        steps{
           sh "docker build -f devops/Dockerfile -t venky005/boardgame1:${BUILD_NUMBER} ."
        }
    }

    stage('Trivy Image Scan'){
        steps{
           sh "trivy image --severity HIGH,CRITICAL --exit-code 1 venky005/boardgame1:${BUILD_NUMBER}"
        }
    }
  }      
}

